### ISSUE TITLE
Demo in the readme doesn't work

### ISSUE THREAD

**Issue by kcalvinalvin** [benjaminmcdonald/global-temps#1]
The demo [link](https://global-temp.herokuapp.com/) shows the following

<img width="542" alt="Screen Shot 2020-10-26 at 4 56 30 PM" src="https://user-images.githubusercontent.com/37185887/97147034-353dfa00-17ac-11eb-8a02-1b390c787064.png">

**Comment by sudo-ben** [comment]
Fixed thanks
